#!/usr/bin/env node

const bots = require('./../services/bots.js')
const requests = require('./../services/requests')
const files = require('./../services/files')


var branch = process.argv[2]
var foo = process.argv[3]


const deplyBot = (branch_name, foo)=> {
    console.log('Date of deploy: ' + Date.now())
    console.log('Deployed branch: ' + branch_name)

    requests.deploySlotRequest('SlotTypeOne', (data)=> {
        console.log('Slot version deployed', data.version)

        requests.deployIntentRequest('IntentOne', (data)=> {
            console.log('Intent version deployed', data.version)

            requests.deployBotRequest('BotOne', (data)=> {
                console.log('Bot version eployed', data.version)

                return (foo === 'yes') ? process.exit(0) : process.exit(1)
            }, 2000)

        }, 2000)

    }, 2000)
}

const deploySlots = (branch_name)=> {
    const slotFolder = './../repos/slots'
    files.processFiles(slotFolder, (files)=> {
        // console.log(files)
        files.map((file)=> {
            requests.deploySlotRequest(file, (data)=> {
                console.log(data.version)
            })
        })

    })
}

deploySlots(branch)

// deplyBot(branch, foo)
