#!/usr/bin/env node

const bots = require('./../services/bots.js')

var branch = process.argv[2]
var foo = process.argv[3]


const test = (branch_name, foo)=> {
    console.log('ceva: ' + branch_name)

    bots.getBotVersions((data)=> {
        setTimeout(()=> {
            bots.putBot(data.checksum, (data)=> {
                setTimeout(()=> {
                    bots.createBotVersion(data.checksum, (data)=> {
                        console.log(data)
                        return (foo === 'yes') ? process.exit(0) : process.exit(1)
                    })
                }, 500)
            })
        }, 500)
    })

    // return (foo === 'yes') ? process.exit(0) : process.exit(1)
}

test(branch, foo)
