#!/usr/bin/env node

var branch = process.argv[2]

const test = (branch_name)=> {
    console.log('ceva: ' + branch_name)
}

const getBranch = ()=> {
    exec("git rev-parse --abbrev-ref HEAD | grep -E '^t[0-9]{2,16}\_.*_[A-Za-z]{2,2}$' | wc -c", function(err, stdout, stderr) {
        console.log(stdout)
    })
}

test(branch)

console.log(process.argv)
